#!/usr/bin/env bash
# ============================================================================
#  Special Fare — Supabase .env setup helper
#  Prompts for your Supabase database password (input hidden),
#  percent-encodes special characters, and writes a ready-to-use .env
#  configured for your Supabase project.
#
#  Usage:  bash deploy/setup-supabase.sh
# ============================================================================

set -euo pipefail
GREEN='\033[0;32m'; CYAN='\033[0;36m'; YELLOW='\033[1;33m'; BOLD='\033[1m'; NC='\033[0m'
ok()   { echo -e "${GREEN}✓${NC} $1"; }
info() { echo -e "${CYAN}ℹ${NC} $1"; }
warn() { echo -e "${YELLOW}⚠${NC} $1"; }

# Your Supabase project reference (from the connection string you shared)
SB_HOST="db.iqqaafsyhpwfuucueftz.supabase.co"
SB_PORT="5432"
SB_DB="postgres"
SB_USER="postgres"

echo -e "${BOLD}${CYAN}═══ Special Fare — Supabase setup ═══${NC}\n"
echo "This will create a .env file configured for your Supabase project:"
echo "  Host: $SB_HOST"
echo ""

# Prompt for password (hidden input)
read -rs -p "Enter your Supabase database password: " SB_PASS
echo
read -rs -p "Confirm password: " SB_PASS_CONFIRM
echo
if [[ "$SB_PASS" != "$SB_PASS_CONFIRM" ]]; then
  echo "✗ Passwords don't match. Aborting."
  exit 1
fi
if [[ -z "$SB_PASS" ]]; then
  echo "✗ Password cannot be empty. Aborting."
  exit 1
fi

# Percent-encode special characters in the password
# Order matters: encode % first, then others
ENCODED_PASS=$(printf '%s' "$SB_PASS" | sed -e 's/%/%25/g' \
  -e 's/@/%40/g' \
  -e 's/#/%23/g' \
  -e 's/\//%2F/g' \
  -e 's/:/%3A/g' \
  -e 's/\?/%3F/g' \
  -e 's/&/%26/g' \
  -e 's/=/%3D/g' \
  -e 's/+/%2B/g' \
  -e 's/ /%20/g' \
  -e 's/\$/%24/g' \
  -e 's/!/%21/g' \
  -e 's/*/%2A/g' \
  -e "s/'/%27/g" \
  -e 's/(/%28/g' \
  -e 's/)/%29/g' \
  -e 's/;/%3B/g' \
  -e 's/,/%2C/g')

# Build the connection string
CONN_STRING="postgresql://${SB_USER}:${ENCODED_PASS}@${SB_HOST}:${SB_PORT}/${SB_DB}"

# Generate a session secret
SECRET=$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p -c 64)

# Prompt for admin creds (with defaults)
echo ""
read -p "Admin email [you@example.com]: " ADMIN_EMAIL
ADMIN_EMAIL="${ADMIN_EMAIL:-you@example.com}"
read -p "Admin name [Special Fare Admin]: " ADMIN_NAME
ADMIN_NAME="${ADMIN_NAME:-Special Fare Admin}"
read -rs -p "Admin password [choose-a-strong-password]: " ADMIN_PASSWORD
ADMIN_PASSWORD="${ADMIN_PASSWORD:-choose-a-strong-password}"
echo

# Determine the app directory (parent of deploy/)
APP_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${APP_DIR}/.env"

# Backup existing .env if present
if [[ -f "$ENV_FILE" ]]; then
  cp "$ENV_FILE" "${ENV_FILE}.backup.$(date +%s)"
  warn "Existing .env backed up"
fi

# Write the new .env
cat > "$ENV_FILE" <<EOF
# Special Fare — Supabase configuration
# Generated by deploy/setup-supabase.sh on $(date)

# Supabase PostgreSQL connection (password is percent-encoded)
DATABASE_URL=${CONN_STRING}
DATABASE_URL_NON_POOLING=${CONN_STRING}

# Session signing secret
SESSION_SECRET=${SECRET}

# Runtime
NODE_ENV=production
PORT=3000
HOSTNAME=127.0.0.1

# Admin account (used by scripts/seed.ts and scripts/create-admin.ts)
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_NAME=${ADMIN_NAME}
EOF

ok ".env written to ${ENV_FILE}"
echo ""
echo -e "${BOLD}Next steps:${NC}"
echo "  1. npx prisma generate      # generate the Prisma client"
echo "  2. npx prisma db push       # create all tables in Supabase"
echo "  3. npx tsx scripts/seed.ts  # seed demo data + your admin account"
echo "  4. npm run build            # build the production app"
echo "  5. npm start                # run it (or pm2 start .next/standalone/start.sh --name special-fare)"
echo ""
info "Verify in Supabase Dashboard → Table Editor → you should see User, Flight, FixedDeparture, Booking, Payment tables."
